# Generated by Django 4.1.5 on 2023-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfuser', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
