# Generated by Django 4.1.5 on 2023-05-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('turfuser', '0003_contact_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfuser'),
        ),
    ]
