# Generated by Django 4.2 on 2023-04-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=100)),
                ('date_for_book', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('turf_image', models.ImageField(upload_to='image/testimagemodel/')),
            ],
        ),
    ]
