# Generated by Django 4.1.5 on 2023-04-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('turf_image', models.ImageField(upload_to='image/testimagemodel/')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfmanager')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=100)),
                ('date_for_book', models.DateField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfmanager')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.turf')),
                ('turf_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfuser')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.turf')),
            ],
        ),
    ]
