# Generated by Django 4.1.5 on 2023-04-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(upload_to='image/testimagemodel/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('game', models.CharField(max_length=100)),
                ('event_title', models.CharField(max_length=200)),
                ('entry_fee', models.CharField(max_length=100)),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.turf')),
            ],
        ),
    ]
