# Generated by Django 4.1.7 on 2023-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_image',
            field=models.ImageField(upload_to='image/testimagemodel/'),
        ),
    ]
