# Generated by Django 4.1.5 on 2023-04-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='strength',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
