# Generated by Django 4.1.7 on 2023-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
