# Generated by Django 4.1.5 on 2023-04-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('manager', '0003_event_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfmanager'),
        ),
    ]
