# Generated by Django 4.1.5 on 2023-04-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='turf',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
