# Generated by Django 4.1.7 on 2023-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_timeslot_turf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
