# Generated by Django 4.1.7 on 2023-04-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_timeslot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.turf')),
            ],
        ),
    ]
