# Generated by Django 4.1.5 on 2023-04-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('manager', '0006_eventbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.turfmanager'),
        ),
    ]
